### ISSUE TITLE
cross-repo linting

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/meta#220]
We have a lot of repos and should probably `lint` them in similar ways. 

Things to consider: 

- rather than warnings and suggestions for formatting, we could have the linter make the commits for us 
  - [pre-commit](https://pre-commit.com/) linting on push
  - other considerations for this? times we should avoid it?

- [super-linter](https://github.com/super-linter/super-linter) supports ESLint and flake8
  - we could set up one config in this repo, and reference it in other repos

```
name: Lint

on: [push, pull_request]

jobs:
  lint:
    uses: meta/.github/workflows/super-linter.yml@main
```
